# This creates a docker container with source code for all packages and all
# dependencies installed.
package-awell-build:
  extends:
    - .build-docker-image
  stage: .pre
  except:
    - tags
  variables:
    AWELL_VERSION: $CI_COMMIT_SHORT_SHA
    DOCKER_FILE_PATH: '$CI_PROJECT_DIR/Dockerfile'
    DOCKER_IMAGE_NAME: <BUILD_IMAGE_NAME>